"""empty message

Revision ID: 5684ed3ffe91
Revises: 90368989431d
Create Date: 2021-11-06 12:23:18.402790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5684ed3ffe91'
down_revision = '90368989431d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('booking_user_id_fkey', 'booking', type_='foreignkey')
    op.drop_column('booking', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('booking_user_id_fkey', 'booking', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
