"""empty message

Revision ID: 720657f62152
Revises: b96cb1890c0e
Create Date: 2021-10-09 11:21:04.029887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720657f62152'
down_revision = 'b96cb1890c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('photo', sa.String(length=120), nullable=True),
    sa.Column('length', sa.String(length=120), nullable=False),
    sa.Column('profile', sa.String(length=120), nullable=False),
    sa.Column('map', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_content', sa.String(length=1000), nullable=True),
    sa.Column('date', sa.String(length=120), nullable=False),
    sa.Column('photo', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('length', sa.String(length=120), nullable=False),
    sa.Column('difficulty', sa.String(length=120), nullable=False),
    sa.Column('photo', sa.String(length=120), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_route',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'route_id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('date', sa.String(length=120), nullable=False),
    sa.Column('user_comments', sa.Integer(), nullable=True),
    sa.Column('post_comments', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_comments'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_comments'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hostel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_stage',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'stage_id')
    )
    op.create_table('user_hostel',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('hostel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'hostel_id')
    )
    op.drop_constraint('user_age_key', 'user', type_='unique')
    op.drop_constraint('user_city_key', 'user', type_='unique')
    op.drop_constraint('user_country_key', 'user', type_='unique')
    op.drop_constraint('user_name_key', 'user', type_='unique')
    op.drop_constraint('user_surname_key', 'user', type_='unique')
    op.drop_column('user', 'surname')
    op.drop_column('user', 'age')
    op.drop_column('user', 'country')
    op.drop_column('user', 'city')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('country', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('surname', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_surname_key', 'user', ['surname'])
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    op.create_unique_constraint('user_country_key', 'user', ['country'])
    op.create_unique_constraint('user_city_key', 'user', ['city'])
    op.create_unique_constraint('user_age_key', 'user', ['age'])
    op.drop_table('user_hostel')
    op.drop_table('user_stage')
    op.drop_table('hostel')
    op.drop_table('comment')
    op.drop_table('user_route')
    op.drop_table('stage')
    op.drop_table('post')
    op.drop_table('route')
    # ### end Alembic commands ###
