"""empty message

Revision ID: 7db4c66aa882
Revises: 75a9cd45cfd2
Create Date: 2021-10-25 14:23:46.743637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db4c66aa882'
down_revision = '75a9cd45cfd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('photo', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'photo')
    # ### end Alembic commands ###
