"""empty message

Revision ID: 86358c7205f3
Revises: ff5aea915b71
Create Date: 2021-10-23 05:14:40.934830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86358c7205f3'
down_revision = 'ff5aea915b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'photo')
    op.drop_column('user', 'profile_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_picture', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('photo', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
