"""empty message

Revision ID: 88011f1e0b16
Revises: 2807edd385a2
Create Date: 2021-09-30 22:07:23.589265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88011f1e0b16'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
