"""empty message

Revision ID: 90368989431d
Revises: e293e00a9c3e
Create Date: 2021-11-06 10:37:28.611330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90368989431d'
down_revision = 'e293e00a9c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'booking', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_column('booking', 'user_id')
    # ### end Alembic commands ###
