"""empty message

Revision ID: a375dbe9354e
Revises: b96cb1890c0e
Create Date: 2021-10-09 08:50:25.441108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a375dbe9354e'
down_revision = 'b96cb1890c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=300), nullable=True),
    sa.Column('date', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hostel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_content', sa.String(length=1000), nullable=True),
    sa.Column('date', sa.String(length=120), nullable=False),
    sa.Column('photo', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('photo', sa.String(length=120), nullable=True),
    sa.Column('length', sa.String(length=120), nullable=False),
    sa.Column('profile', sa.String(length=120), nullable=False),
    sa.Column('map', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('length', sa.String(length=120), nullable=False),
    sa.Column('difficulty', sa.String(length=120), nullable=False),
    sa.Column('photo', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('user_age_key', 'user', type_='unique')
    op.drop_constraint('user_city_key', 'user', type_='unique')
    op.drop_constraint('user_country_key', 'user', type_='unique')
    op.drop_constraint('user_name_key', 'user', type_='unique')
    op.drop_constraint('user_surname_key', 'user', type_='unique')
    op.drop_column('user', 'country')
    op.drop_column('user', 'surname')
    op.drop_column('user', 'city')
    op.drop_column('user', 'age')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('surname', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('country', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_surname_key', 'user', ['surname'])
    op.create_unique_constraint('user_name_key', 'user', ['name'])
    op.create_unique_constraint('user_country_key', 'user', ['country'])
    op.create_unique_constraint('user_city_key', 'user', ['city'])
    op.create_unique_constraint('user_age_key', 'user', ['age'])
    op.drop_table('stage')
    op.drop_table('route')
    op.drop_table('post')
    op.drop_table('hostel')
    op.drop_table('comment')
    # ### end Alembic commands ###
