"""empty message

Revision ID: b96cb1890c0e
Revises: 88011f1e0b16
Create Date: 2021-10-03 20:12:01.630567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96cb1890c0e'
down_revision = '88011f1e0b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('surname', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('country', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('city', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['surname'])
    op.create_unique_constraint(None, 'user', ['age'])
    op.create_unique_constraint(None, 'user', ['country'])
    op.create_unique_constraint(None, 'user', ['city'])
    op.create_unique_constraint(None, 'user', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'city')
    op.drop_column('user', 'country')
    op.drop_column('user', 'age')
    op.drop_column('user', 'surname')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
