"""empty message

Revision ID: c6ae372c280b
Revises: eb32e55b8d20
Create Date: 2021-11-05 23:02:00.542077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ae372c280b'
down_revision = 'eb32e55b8d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'booking', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_column('booking', 'user_id')
    # ### end Alembic commands ###
